### ISSUE TITLE
`util.parse` should support accessing tags, which would require a less restrictive regex

### ISSUE THREAD

**Issue by gaurav** [aai-institute/lakefs-spec#299]
`util.parse()` currently assumes that the branch name is "Only letters, digits, underscores and dash, no leading dash."

https://github.com/aai-institute/lakefs-spec/blob/06134be76122834f197aba1e3fee89628e66236d/src/lakefs_spec/util.py#L118-L130

However, users might want to use [a tag name](https://docs.lakefs.io/understand/model.html#tags) instead of a branch name, which has a [much more complicated syntax](https://git-scm.com/docs/git-check-ref-format). Notably, the current regex doesn't match the two example tags in the LakeFS docs (`v2.3` and `dev-jane-before-v2.3-merge`). It might also be useful to support [ref expressions](https://docs.lakefs.io/understand/model.html#ref-expressions).

I would suggest making the regex less restrictive -- at a minimum `(\w[\w\-\.]*)`, but possibly going all the way to support ref expressions to include `[~^]`. The error could also be rewritten to be a bit clearer (e.g. because `lakefs.ls(...)` calls this after calling `_strip_protocol()`, I get the following error message: `ValueError: expected path with structure lakefs://<repo>/<ref>/<resource>, got 'heal-studies/v2.0/'` -- which made me think that I had forgotten to add the `lakefs://` prefix before realizing that the branch was being rejected for being incorrect).

Alternatively, if I'm misunderstanding how tags and ref expressions should be used in lakefs-spec, please let me know -- and thank you so much for building this great library!

**Comment by nicholasjng** [comment]
Thank you for the detailed report! 

Since we want to fully implement lakeFS's URI specification, we must also match their support for ref expressions. Your regex suggestion sounds great, would you be willing to send a PR?

I agree that the error message is a bit sparse, and even misleading in the case you presented. We might need to check our callsites for the order of `util.parse()` and `_strip_protocol()` - alternatively, we could decide to split the protocol off the template path if the input doesn't have one, so we don't confuse people with the protocol unnecessarily.

**Comment by gaurav** [comment]
This works great now, thanks so much for the quick fix!
